name: First Workflow
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Running a simple Github Action
        run: echo "this workflow needs to run"
        
      - name: simulating error
        run: echo "error taking place"; exit 1
