name: First Workflow
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v3
      - name: Running a simple Github Action
        run: echo "this workflow needs to run"
